version: '3'

services:
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: mongodb://db:27017/authdb
    depends_on:
      - db
  db:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: authdb
    volumes:
      - ./mongo:/data/db
  